### ISSUE TITLE
@rheadkid (important)

### ISSUE THREAD

**Issue by hegemonkhan** [KVonGit/Quest-Group_Project#27]
I don't know github yet, so hopefully I didn't f' up stuff, but I tried to add this code, to the code forum/board, but I don't understand this branch/push/pull stuff... I think I have my code as a pull request in one of the branches (hegemonkhan/patch_1 or rhead/patch_1), argh... I need to learn how to use github... I hope whatever I did is fixable... sorry about whatever mess I caused... just started clicking on stuff thinking I'd be able to understand what I'm doing... nope... argh.

I think I merged the 'master' and 'patch_1' branch too... hopefully didn't f'up it, hopefully you can undo/fix whatever I did... argh ... so sorry about all this, need to learn how github works, before I try messing around with it.

anyways, here's the code of mine:

(this is the most updated/corrected/fixed-up version too, so use this code to copy and paste where-ever/how-ever you want to put it at)

```
// I just used this 'dynamic_menu_function' code for 'character creation' stuff as my example here of it, but it can be tweaked to be used for anything, such as dialogue/conversation/topics too, and/or whatever else as well
// some of the parameters can be removed/adjusted/tweaked, this is just an example.
// also, I used a Function for this example, but we can use Objects and their Script Attributes, and Delegates, instead

<game name="example_game">
  <attr name="sex_stringlist_attribute" type="simplestringlist">male;female</attr>
  <attr name="human_race_stringlist_attribute" type="simplestringlist">european;african;asian;arabian;american;australian</attr>
  <attr name="start" type="script">
    dynamic_menu_function ("Sex?", game.sex_stringlist_attribute, player, "sex_string_attribute")
    on ready {
      dynamic_menu_function ("Race?", game.human_race_stringlist_attribute, player, "race_string_attribute")
    }
  </attr>
</game>

<object name="room">
</object>

<object name="player">
  <attr name="parent" type="object">room</attr>
  <attr name="sex_string_attribute" type="string">unknown</attr>
  <attr name="race_string_attribute" type="string">unknown</attr>
</object>

<function name="dynamic_menu_function" parameters="menu_prompt_string_parameter, object_dot_attribute_stringlist_parameter, name_of_object_parameter, name_of_attribute_parameter">
  <![CDATA[
    ClearScreen
    msg (menu_prompt_string_parameter)
    msg ("(Type in the number of your choice)")
    msg ("")
    msg ("0. random")
    numbering_integer_variable = 0
    foreach (item_variable, object_dot_attribute_stringlist_parameter) {
      numbering_integer_variable = numbering_integer_variable + 1
      msg (numbering_integer_variable + ". " + item_variable)
    }
    get input {
      ClearScreen
      if (IsInt (result)) {
        input_integer_variable = ToInt (result)
        list_count_integer_variable = ListCount (object_dot_attribute_stringlist_parameter)
        last_index_number_integer_variable = list_count_integer_variable - 1
        if (input_integer_variable = 0) {
          randomly_selected_item_string_variable = StringListItem (object_dot_attribute_stringlist_parameter, GetRandomInt (0, last_index_number_integer_variable))
          set (name_of_object_parameter, name_of_attribute_parameter, randomly_selected_item_string_variable)
        } else if (input_integer_variable > 0 and input_integer_variable < list_count_integer_variable) {
          selected_item_string_variable = StringListItem (object_dot_attribute_stringlist_parameter, input_integer_variable)
          set (name_of_object_parameter, name_of_attribute_parameter, selected_item_string_variable)
        } else { // if input is 'out of bounds' (wrong input, try again)
          dynamic_menu_function (menu_prompt_string_parameter, object_dot_attribute_stringlist_parameter, name_of_object_parameter, name_of_attribute_parameter)
        }
      } else { // if not IsInt (wrong input, try again)
        dynamic_menu_function (menu_prompt_string_parameter, object_dot_attribute_stringlist_parameter, name_of_object_parameter, name_of_attribute_parameter)
      }
    } // end of 'get input'
  ]]>
</function>
```

**Comment by rheadkid** [comment]
Welcome to the club, sir!

I know two things about GitHub:
1. Jack
2. Shit

Well, maybe I know a little...

If you made a fork and did all that in the fork, it would look like you saved it to the main file when you pressed that last button!

I'm sorry, but I'm laughing my ass off because I sent the SAME EXACT MESSAGE you just sent me to the guy who ran the repo I made my first (and only) pull request to.

I didn't mess his stuff up, and I'm sure you didn't mess this up either.

Even if you did, GitHub keeps all the revisions so we can just revert that shit!

It's all gravy, as they say in the KFC!

---
I'm burnt out for the night, but I'm gonna check your code out in the morning!

**Comment by hegemonkhan** [comment]
thanks, glad to hear whatever I did can be undone... sorry about jumping into trying to use github, without leanring how it works... I'll just stick to the 'issues' (forum thread/posts) for now, as I think I got that figured out correctly and haven't messed anything up with it... so, until then, I'll just make threads in the issues forum/board if I got code, and then you can copy/paste it where-ever/how-ever, until I understand how github works.

**Comment by rheadkid** [comment]
@hegemonkhan 

Don't sweat it at all! 

I wasn't really laughing AT you, I honestly did the same thing just 2 months ago.

I asked Pixie about GitHub procedure earlier, and he said HE just figured out how to post the updates less than 6 months ago.

And DarkLizerd just created an account today, so I assure you: we are all in the same boat in this one.

PLUS, all the files stay backed up. 

PLUS I save back-ups and originals.

And Pixie has a separate repo, and his own originals (and backups too, I'm sure).

AND between us, we could easily remove the offending code.

Just wait until I try to submit something, that'll be funny, too!

**Comment by ThePix** [comment]
> I hope whatever I did is fixable

None of us are experts, but the big thing about Github is you can revert all changes so no one can mess up badly.

**Comment by rheadkid** [comment]
I think I just need to click COMMIT on that pull request.

Have you looked at that file, @ThePix ?

**Comment by hegemonkhan** [comment]
my programming classes and many peers, use github (it is very useful software/website for drafting/ideas/editing/versioning-updating, be it coding or other stuff), but I've been lazy and not gotten around to learning it yet, as you obviously saw here, lol.

**Comment by XanMag** [comment]
Yea... this whole github/adding code thing is totally new to me.  So, forgive me if I ask dumb questions, ask for guidance, or ask for guidance on dumb questions.
