### ISSUE TITLE
'Cheat/Debugging/Testing' system

### ISSUE THREAD

**Issue by hegemonkhan** [KVonGit/Quest-Group_Project#31]
it's helpful to have 'cheats' (Commands) and/or a 'debug' room (though, I'm not really familiar with how this works or is done, but some professional game makers do/use it), either for the person playing the game to use and/or for us for debugging/testing stuff in game, for example, a cheat to go to whatever location we want, so we can test that location in game-play, and see if it works (we don't want to have to play through the entire game up to the point we want to test, lol). Another example is being able to modify stats for testing game balance and/or our game mechanic equations if they handle properly different stat amounts.

----------

though, if we don't want cheats to be available for people playing the game, we need to remember to remove them... unlike some mistakes by some professional game makers... as players will find them if they're left in...

**Comment by rheadkid** [comment]
```up up down down left right left right B A SELECT```

You can type that in in the Inform version of They Call Ya MIster to gain extra health.

Bwahahahaha!

---
Pixie's got this on his wiki:

https://github.com/ThePix/quest/wiki/Cheating

---
And they'll definitely be removed.

We'll label them all CHEAT in the name or  a note, and I can find them all easily and delete the corresponding lines.

**Comment by hegemonkhan** [comment]
do we want to leave in cheats in for the person playing the game, or not?

(but any of our cheats for testing/debugging, definately must be removed, lol)

**Comment by rheadkid** [comment]
Well... we may decide to leave  a cheat or two in there... We'll have to vote on that one.

But yeah, the Konami code (popularly known as the Contra code, although it worked on most (if not all) Konami games) was for testing and the left it in, for whatever reason.

We'll definitely, definitely avoid that.

---
Someone did mention setting up XYZZY to do different things in different scenarios. That's a pretty good idea, considering it's a default command.

Just like you guys hadn't heard of FROTZ (which means you haven't played the Enchanter Trilogy, which is BAD!), I hadn't heard of XYZZY.

I've tried to play 5 or 6 Scott Adams games, but they aren't my cup of tea... I believe he originated the spell, but I may be mistaken.

**Comment by ThePix** [comment]
You could set a Boolean on the game object to true, and check that in your cheats. When the games are combined, that attribute will be missing, so your cheats will not work.

**Comment by rheadkid** [comment]
I'm closing this one out.

Sounds resolved to me.

Boolean!
