### ISSUE TITLE
Full text? or picture and sounds?

### ISSUE THREAD

**Issue by DarkLizerd** [KVonGit/Quest-Group_Project#67]
"A picture is worth a thousand words"
Had this thought today... Would we want the top half of the screen to have a picture of the location the player is in? It could add a bit of color to the story.
How about sound?
.>Shoot zombie
(play sound: gun shot)
The zombie staggers, then falls down.

You are following the path by the river...
(play sound: babbling brook) (No, river, not Brook!)

You force open the old door with the rusted hinges...
(play sound: creek)

**Comment by rheadkid** [comment]
I don't know...

I always find images and audio awesome at first, then annoying the rest of the way through a game...

Usually is the key word.

There are always exceptions.

---
My main gripe is the map/picture taking up space. I usually like to read back up a few commands before making a move, just to be sure I didn't miss/misread anything.

---
As long as we include an option for the player to turn these off and on, I have no objections.

**Comment by XanMag** [comment]
Also have to consider the space limitation for Quest uploads.  I'm flexible either way...

**Comment by rheadkid** [comment]
Can anyone draw?

There's an images folder in the master repo... put whatever you've got in there! 

We can all check it out!

**Comment by XanMag** [comment]
Meh.  I'm okay with stuff.  Give me a theme.

**Comment by rheadkid** [comment]
DL is the Master of Ideas...


...but I'll give it a shot.

A blue phone-booth, high up on a rocky promontory.

**Comment by DarkLizerd** [comment]
I can't even draw stick men badly...
But, someone has picture and sound files.
I do like the option of turning them on and off...

**Comment by rheadkid** [comment]
Just so you guys are prepared:

I plan (maybe) to have a location: [THE DEVIL'S TOWER](https://en.wikipedia.org/wiki/Devils_Tower), where you must examine the stars above (the Pleiades) before the blue phone-booth appears. (If we're still going that route.)

---
That's ~~~where the previous 'theme' idea came~~~ from whence the previous 'theme' idea came.

(I'm watching Cosmos right now. It  gives me too many ideas to jot down!)

**Comment by rheadkid** [comment]
> DL is the Master of Ideas...
> 
> ...but I'll give it a shot.
> 
> A blue phone-booth, high up on a rocky promontory.


Just to be clear: this was me giving XM a example for an example theme; not me saying I'm drawing this up. (I can't draw stick men either! You should see the maps I make during text adventures, too! They are HILARIOUS!!!)

**Comment by KVonGit** [comment]
We decided to go full text; correct?
