### ISSUE TITLE
HK

### ISSUE THREAD

**Issue by KVonGit** [KVonGit/Quest-Group_Project#79]
Can anyone see HK's comments and such?

I spoke with him on the textadventures site, and he said he's committing codes and commenting on issues, but I can't see any of that or that he even exists...

When I click on his name, I get a 404 error...

Anyone else having my problem?

Click on the below link. It's a commit by HK, with a link to his profile.

https://github.com/KVonGit/Quest-Group_Project/blob/59f3e9cc60206661422f9cf0a4247495a50d57ee/dynamic_menu_function

**Comment by ThePix** [comment]
I have not seen any comments by HK... But i am limited to my phone and suspect i am not seeing quite a bit.

**Comment by XanMag** [comment]
Nope.  HK is in the Bermuda Triangle... 

    On Wednesday, August 16, 2017 6:13 AM, ThePix <notifications@github.com> wrote:
 

 I have not seen any comments by HK... But i am limited to my phone and suspect i am not seeing quite a bit.—

**Comment by KVonGit** [comment]
I've spoken with him.

1. He's busy with school.
2. He set his GitHub account up as 'private'. He can see these conversations and our commits. In fact, he said he makes comments in the issues and has made a couple of commits, but something is messed up. (Possibly forked up?)
3. He dropped out of the project just now, mainly because of school. I told him we'd consider him on 'indefinite leave' and credit him as a special guest collaborator/lurker. (He said he'll still lurk and chime in on the forum when he gets the chance.)

---
Good luck with the schooling, HK!

**Comment by XanMag** [comment]
I will make progress on the game soon.  I've been busy as school just fired up again.  I'll add some things this weekend for sure.  I'm glad we are not in a hurry!  :)
