### ISSUE TITLE
All work and no play...

### ISSUE THREAD

**Issue by KVonGit** [KVonGit/Quest-Group_Project#80]
# What is everyone's favorite meal?

Mine's spaghetti. (The Italian guy likes spaghetti... SURPRISE!)

---

#### This segue was brought to you by:

#  &infin; SHARDS

or 

# SHARDS OF INFINITY

(or something like that)

**Comment by XanMag** [comment]
The oft accused of being Mexican but not Mexican guy likes fish tacos.

A segue into an appropriate food-related title for the game:  

The Sharts of Infinity

**Comment by KVonGit** [comment]
>The oft accused of being Mexican but not Mexican guy...

Ah! I have the same thing happen! (Dark sun-tan, and all...)

I had to buy Rosetta Stone to live up to my appearance!

> fish tacos

If I ever reference eating 'fish tacos', I ain't talkin' 'bout food!

But seriously: I've never seen an _actual_ ...

You know what? Nevermind! (I've joked myself into a corner... Just know this: I've **definitely** seen more than my share of fish tacos!)

>The Sharts of Infinity

# The Sharts of Infinity (with audio!)
### **INFINITE EDITION** WITH SCRATCH & SNIFF FEELIES AVAILABLE WHILE SUPPLIES LAST!!!

**Comment by DarkLizerd** [comment]
Chinese...
("Chinese food" also counts...)
